#ifndef _MACH_ARM_VM_PARAM_H_
#define _MACH_ARM_VM_PARAM_H_

#define BYTE_SIZE 8

#define ARM_PGBYTES 4096
#define ARM_PGSHIFT 12

#define PAGE_SIZE ARM_PGBYTES
#define PAGE_SHIFT ARM_PGSHIFT
#define PAGE_MASK (PAGE_SIZE - 1)

#endif
