#ifndef _MACHINE_X86_LIMITS_H_
#define _MACHINE_X86_LIMITS_H_

#define CHAR_BIT 8

#define UINT_MAX 0xFFFFFFFF
#define INT_MAX 2147483647
#define INT_MIN (-INT_MAX - 1)

#ifdef __LP64__
#define ULONG_MAX 0xFFFFFFFFFFFFFFFFUL
#define LONG_MAX 0x7FFFFFFFFFFFFFFFL
#else
#define ULONG_MAX 0xFFFFFFFFUL
#define LONG_MAX 2147483647L
#endif
#define LONG_MIN (-LONG_MAX - 1)

#define ULLONG_MAX 0xFFFFFFFFFFFFFFFFULL
#define LLONG_MAX 0x7FFFFFFFFFFFFFFFLL
#define LLONG_MIN (-LLONG_MAX - 1)

#endif
